# Generated by Django 6.0.4 on 2026-04-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=255)),
                ('gameName', models.CharField(max_length=255)),
                ('tagLine', models.CharField(max_length=255)),
            ],
        ),
    ]
